# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: taskiq-postgres
repo_url: https://github.com/danfimov/taskiq-postgres
repo_name: taskiq-postgres
edit_uri: edit/main/docs/

nav:
  - Overview:
      - index.md
  - Tutorial:
      - tutorial/quickstart.md
      - tutorial/broker.md
      - tutorial/schedule_source.md
  - API:
      - reference.md
  - Contributing:
      - contributing.md


theme:
  name: material
  language: ru
  favicon: assets/favicon.svg
  features:
    - toc.follow
    - toc.integrate
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.path
    - content.action.edit
    - content.code.annotate
    - content.code.select
    - content.code.copy
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Use light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Use dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Use system colors

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  links:
    absolute_links: relative_to_docs

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - admonition
  - md_in_html  # for badges in readme.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]
          options:
            docstring_style: google
            filters:
              - '!^_'
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true
            docstring_section_style: list
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
