name: Release

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g. v1.2.3
      - v*

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"
          version: "latest"
      - run: uv version "${{ github.ref_name }}"
      - run: uv build
      - run: uv publish --trusted-publishing always
